version: '3.8'

services:
  environment-context-analyser-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./src/api/model:/app/src/api/model
    tty: true
    restart: always
    cpus: 4
    mem_limit: 2000MB
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia  
    networks:
      - default
